In [3]:
## importing models
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB 
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import  AdaBoostClassifier
import pandas as  pd

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")
import os

In [4]:
df=pd.read_csv('heart.csv')
rows=df.shape[0]
columns=df.shape[1]

print ( rows,columns )
## input Variables = x
## output variables = y 

y=df['target']

x=df.drop('target',axis=1)
x

303 14

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [5]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
## input Variables = x
## output variables = y 

y=df['target']

x=df.drop('target',axis=1)
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [7]:
## test and Train Split

X_train,X_test,y_train, y_test = train_test_split( x,y,test_size=.25,random_state=42323232)

In [8]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()
nbg_clf = GaussianNB()

In [9]:
for clf in (log_clf, nbg_clf, rnd_clf, svm_clf):
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.8157894736842105
GaussianNB 0.8157894736842105
RandomForestClassifier 0.7631578947368421
SVC 0.6578947368421053

In [10]:
from sklearn.svm import SVC
svc_clf= SVC( probability =True,kernel='linear')

### AdaBoostClassifier with SVM

In [12]:
boost = AdaBoostClassifier( estimator=svc_clf, n_estimators=500,algorithm='SAMME',learning_rate=.5)

boost.fit(X_train, y_train)

y_pred = boost.predict(X_test)

print("Bagging with Random Forest Classifier :Accuracy ", accuracy_score(y_test, y_pred))

Bagging with Random Forest Classifier :Accuracy  0.8421052631578947

In [13]:
## Training Score

boost.score(X_train,y_train)

0.801762114537445

In [14]:
## Testing Score

boost.score(X_test,y_test)

0.8421052631578947

### AdaBoostClassifier with Decision Tree

In [18]:
boost = AdaBoostClassifier( estimator=DecisionTreeClassifier(max_depth=1), n_estimators=10,algorithm='SAMME',learning_rate=0.5)

boost.fit(X_train, y_train)

y_pred = boost.predict(X_test)

print("Bagging with Decision Tree Classifier :Accuracy ", accuracy_score(y_test, y_pred))

Bagging with Decision Tree Classifier :Accuracy  0.8157894736842105

In [17]:
## Training Score

boost.score(X_train,y_train)

0.8766519823788547

In [19]:
## Testing Score

boost.score(X_test,y_test)

0.8157894736842105

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
para_grid={
   
    'learning_rate':[1,0.5,0.1,0.01,0.001,1.5,1.2],
    'algorithm':['SAMME','SAMME.R'],
    'n_estimators':[10,50,100,200]
    
}

In [22]:
grid= GridSearchCV(AdaBoostClassifier(),para_grid)

In [23]:
grid.fit(X_train,y_train)

GridSearchCV(estimator=AdaBoostClassifier(),
             param_grid={'algorithm': ['SAMME', 'SAMME.R'],
                         'learning_rate': [1, 0.5, 0.1, 0.01, 0.001, 1.5, 1.2],
                         'n_estimators': [10, 50, 100, 200]})